### PR TITLE
Fixed cron edit invoice list.

### PR DESCRIPTION
**Pull request by fearless359**
The edit was only showing the first 25 invoices in the select list. It
now displays all. Also, the invoice number was added to the information
displayed in the selection list.

### CODE REVIEW

**Comment by twobob** [comment]
Probably the wrong place to mention it (and perhaps you are a 'nix only guy) but have you considered the possibility of a https://blogs.technet.microsoft.com/heyscriptingguy/2015/01/13/use-powershell-to-create-scheduled-tasks/ scheduled tasks alternative to the cron work on windows?

Just a thought :)

**Comment by fearless359** [comment]
All cron is doing is scheduling a task to execute a php command on a repeating cycle (see FAQ in the Information link on the top bar when you are running SI). From what I see of powershell scheduling, you should be able to do the same with it. So have you tried just using powershell to schedule the command for SI running in your localhost web-server?

**Comment by twobob** [comment]
I haven't and utterly could.  You are correct it is totally possible on windows in 'n' ways including native VB, generating native scheduled tasks, via BAT files that run on the system account and doubtless several other hacks, wangles and exception-happy workarounds.  However, that felt like the most "native" way of doing it.    Given the exact command (or way it is constructed) I am happy to point https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/new-scheduledtasksettingsset?view=win10-ps at it and create a frankencommand for windows if that would be helpful

**Comment by fearless359** [comment]
The ability to issue the command from command line is what SI supports. How that command is scheduled is the user's requirement. On a linux server, that is cron. On windows, it can be cron if you install Cygwin or via Powershell or other windows scheduling means if you don't want to install Cygwin.

**Pull request merged**
